version: '3.8'

services:
  universal-data-loader:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    container_name: universal-data-loader
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    volumes:
      # Optional: Mount local directories for persistent storage
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - data-loader-network
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: universal-data-loader-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Optional: SSL certificates
    depends_on:
      - universal-data-loader
    restart: unless-stopped
    networks:
      - data-loader-network
    profiles:
      - production  # Only run with: docker-compose --profile production up

networks:
  data-loader-network:
    driver: bridge

volumes:
  data-loader-data:
    driver: local