# Development Environment Configuration
debug: true
log_level: DEBUG
environment: development

# Server
host: "0.0.0.0"
port: 8000

# Processing
max_workers: 2
job_timeout: 300
max_file_size: 50  # MB

# Storage (development uses local temp)
upload_dir: "/tmp/uploads"
output_dir: "/tmp/outputs"

# Security (relaxed for development)
allowed_origins: ["*"]
rate_limit: "1000/minute"

# Features
enable_metrics: true
ocr_languages: ["eng", "fra", "deu"]