# Production Environment Configuration
debug: false
log_level: INFO
environment: production

# Server
host: "0.0.0.0"
port: 8000

# Processing
max_workers: 4
job_timeout: 600
max_file_size: 100  # MB

# Storage (production uses persistent volumes)
upload_dir: "/app/data/uploads"
output_dir: "/app/data/outputs"

# Security (strict for production)
allowed_origins: []  # Set via environment variable
rate_limit: "100/minute"
api_key: ""  # Set via environment variable

# Features
enable_metrics: true
ocr_languages: ["eng", "fra", "deu", "spa"]